module.exports = Object.freeze({
  RESOURCES_PATH: './src/jsonGenerator/resources/',
  JSON_PATH: './dist/',
  JSON_FILE: 'data.json',
  TASKS_FILE: 'Tasks.xlsx',
  TASKS_SHEET: 'Sheet1',
  TASKS_A: 'task',
  TASKS_B: 'link',
  TASKS_C: 'Status',
  SCORE_FILE: 'Mentor score.xlsx',
  SCORE_SHEET: 'Form Responses 1',
  SCORE_B: 'Ссылка на GitHub ментора в формате: https://github.com/nickname',
  SCORE_C: 'Ссылка на GitHub студента в формате: https://github.com/nickname',
  SCORE_D: 'Таск',
  MENTOR_STUDENTS_FILE: 'Mentor-students pairs.xlsx',
  PAIRS_SHEET: 'pairs',
  PAIRS_A: 'interviewer',
  PAIRS_B: 'student github',
  MENTORS_SHEET: 'second_name-to_github_account',
  MENTORS_A: 'Name',
  MENTORS_B: 'Surname',
  MENTORS_E: 'GitHub',
});
